### ISSUE TITLE
Please support Firefox.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [dom96/chirper.picheta.me#1]

**Comment by dom96** [comment]
Hey! Thanks for reaching out :)

I actually primarily use Firefox so also eager to get this done. But since I created this extension using Manifest v3 I needed  for Manifest v3 support to land in Firefox. Last evening I made some progress to getting it to work, there is still a few changes needed (lack of `:has` selector support in Firefox being a notable one) but should have it ready this week hopefully.

**Comment by beedell-roke** [comment]
Thanks a lot, @dom96.

**Comment by dom96** [comment]
@rokejulianlockhart here you go https://addons.mozilla.org/en-GB/firefox/addon/mastodon-chirper/
